### PR TITLE
 Import the recipe from my cross-platform X.org work. 

### PR DESCRIPTION
**Pull request by pkgw**
This switches the recipe to the form used by my work to build packages of the X.org X11 libraries on all three platforms. There's some boilerplate involved that ends up making this particular recipe a bit more complicated than it needs to be, but I think it's important to keep the recipes as consistent as possible.

Pursuant to conda-forge/xorg-xcb-proto-feedstock#2 and #2 .

### CODE REVIEW

**Comment by pkgw** [comment]
@ccordoba12 @mingwandroid ? Would be good to get the package names ironed out before real users start installing the current `xorg-`  versions of this that are available on conda-forge.

**Comment by ocefpaf** [comment]
> @ccordoba12 @mingwandroid ? Would be good to get the package names ironed out before real users start installing the current `xorg-`  versions of this that are available on conda-forge.

Indeed. @mingwandroid your comments in another issue (sorry I missed which one) gave me the impression that you wanted to move to the `xorg-` prefix in the long term. If so maybe we can just leave @pkgw as is instead of renaming them?

**Comment by pkgw** [comment]
My takeaway from the original discussion ([pthread-stubs-feedstock#3](https://github.com/conda-forge/pthread-stubs-feedstock/issues/3)) was that in princple that would maybe be nice, but it breaks compatibility too much because conda doesn't have a concept of "conflicts" or "deprecation" in package dependencies, and it won't learn how to do things like that on a rapid enough time scale.

**Comment by ccordoba12** [comment]
I don't have problems with this if it doesn't break Qt5. But only a rebuild of Qt5 will verify that.

So merging ;-)

**Comment by mingwandroid** [comment]
Conda is learning about deprecation, so I think sticking to un-prefixed would be better, then using the deprecation feature when we want to change it back again.

But I don't mind too much which way this goes.

**Pull request merged**
